// Generated by CoffeeScript 1.6.2
(function($, window) {
  return $(document).ready(function() {
    $("#main").stylish("scripts/stylish.php");
    return $('#toggle_stylish').on('click', function(e) {
      return $("#main").stylish('toggle');
    });
  });
})(jQuery, window);

/*
//@ sourceMappingURL=demo.map
*/
