// Generated by CoffeeScript 1.6.2
var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

(function($, window) {
  var Stylish, className, templates;

  className = {
    mode: 'stylish-mode',
    wrapper: 'stylish-wrapper',
    inputSelector: 'input-selector',
    inputStyle: 'input-style',
    inputStoredSelectors: 'stored-styles'
  };
  templates = {
    hoverWrapper: "<div class=\"" + className.wrapper + "\"></div>",
    dialog: "<div class=\"stylish popover bottom\">\n	<div class=\"arrow\"></div>\n\n	<div class=\"popover-content\">\n		<small class=\"muted size\"></small>\n		<label>Stored:</label>\n		<select class=\"" + className.inputStoredSelectors + " input-large\"></select>\n		<label>Selector:</label>\n		<input type=\"text\" class=\"" + className.inputSelector + " input-large pull-left\" />\n		<div class=\"btn-toolbar pull-left selector-level\">\n			<div class=\"btn-group\">\n				<a class=\"btn btn-mini select-up\" href=\"#\"><i class=\"icon-circle-arrow-up\"></i></a>\n				<a class=\"btn btn-mini select-down\" href=\"#\"><i class=\"icon-circle-arrow-down\"></i></a>\n			</div>\n		</div>\n		<textarea rows=\"5\" class=\"" + className.inputStyle + " input-xlarge\"></textarea>\n		<div class=\"text-center\">\n			<button class=\"btn btn-save\">Save</button>\n		</div>\n	</div>\n</div>",
    storeSelectorOption: "<option value=\"0\" class=\"muted\">Not stored</option>"
  };
  Stylish = (function() {
    Stylish.prototype.active = false;

    Stylish.prototype.editing = false;

    Stylish.prototype.settings = {};

    Stylish.prototype.$container = void 0;

    Stylish.prototype.$element = void 0;

    Stylish.prototype.$wrapper = void 0;

    Stylish.prototype.$dialog = void 0;

    function Stylish(container, options) {
      this.selectStyle = __bind(this.selectStyle, this);
      this.saveStyles = __bind(this.saveStyles, this);
      this.changeLevel = __bind(this.changeLevel, this);
      this.displayEditor = __bind(this.displayEditor, this);
      this.displayOver = __bind(this.displayOver, this);
      this.setStyleData = __bind(this.setStyleData, this);
      this.setInputValues = __bind(this.setInputValues, this);
      this.closeDialog = __bind(this.closeDialog, this);
      this.getCompleteSelector = __bind(this.getCompleteSelector, this);      this.init(container, options);
    }

    Stylish.prototype.init = function(container, options) {
      if (typeof options === 'string') {
        options = {
          post: options
        };
      }
      this.settings = $.extend({}, this.defaults, options);
      if (!this.settings.post) {
        throw Error('You need to define the \'post\' parameter.');
      }
      this.$container = $(container);
      if (this.$container.is(document) || this.$container.is(window)) {
        this.$container = $('body');
      }
      this.$wrapper = $(templates.hoverWrapper);
      this.$dialog = $(templates.dialog);
      this.$container.append(this.$wrapper).append(this.$dialog);
      this.$container.addClass(className.mode);
      this.$container.on('mouseover', '*', this.displayOver);
      this.$container.on('click', '*', this.displayEditor);
      this.$dialog.on('click', '.selector-level .btn', this.changeLevel);
      this.$dialog.on('click', '.btn-save', this.saveStyles);
      this.$dialog.on('change', "." + className.inputStoredSelectors, this.selectStyle);
      return $.ajax({
        url: this.settings.post,
        data: {
          json: 1
        },
        type: 'GET',
        success: this.setStyleData
      });
    };

    Stylish.prototype.getSelector = function($element) {
      var classNames, id, selector;

      selector = $element[0].nodeName;
      id = $element.attr('id');
      classNames = $element.attr('class');
      if (id) {
        selector += "#" + id;
      }
      if (classNames) {
        selector += "." + ($.trim(classNames).replace(/\s/gi, '.'));
      }
      return selector.toLowerCase();
    };

    Stylish.prototype.getCompleteSelector = function($element, level) {
      var current, parents, selector,
        _this = this;

      parents = $element.parents().map(function(index, element) {
        if (index < level) {
          return _this.getSelector($(element));
        }
      }).get().reverse().join(' > ');
      current = this.getSelector($element);
      selector = parents ? "" + parents + " > " + current : "" + current;
      return selector.replace("." + className.mode, '');
    };

    Stylish.prototype.addStyleToElement = function(selector, style) {
      return $(selector).each(function(index, element) {
        var $this, data;

        $this = $(element);
        data = $this.data('styles');
        if (!data) {
          data = {};
        }
        data[selector] = {
          style: style
        };
        return $this.data('styles', data);
      });
    };

    Stylish.prototype.closeDialog = function() {
      this.editing = false;
      this.$element = null;
      return this.$dialog.hide();
    };

    Stylish.prototype.setInputValues = function(selector) {
      var styleText, styles;

      styles = this.$element.data('styles');
      styleText = "";
      if (styles && styles[selector]) {
        styleText = this.json2Css(styles[selector].style);
      }
      this.$dialog.find("." + className.inputSelector).val(selector);
      this.$dialog.find("." + className.inputStyle).val(styleText);
      return this.$dialog.find("." + className.inputStoredSelectors).val(selector);
    };

    Stylish.prototype.css2Json = function(cssText) {
      var attribute, attributes, index, line, obj, value, _i, _len;

      obj = {};
      attributes = cssText.replace('\n', '').split(';');
      attributes.pop();
      for (_i = 0, _len = attributes.length; _i < _len; _i++) {
        line = attributes[_i];
        index = line.indexOf(':');
        attribute = $.trim(line.substring(0, index));
        value = $.trim(line.substr(index + 1)).replace(';', '');
        obj[attribute] = value;
      }
      return obj;
    };

    Stylish.prototype.json2Css = function(cssJson) {
      var attribute, style, value;

      style = "";
      for (attribute in cssJson) {
        value = cssJson[attribute];
        style += "" + attribute + ": " + value + ";\n";
      }
      return style;
    };

    Stylish.prototype.on = function() {
      this.active = true;
      return this.$wrapper.show();
    };

    Stylish.prototype.off = function() {
      this.active = false;
      return this.$wrapper.hide();
    };

    Stylish.prototype.toggle = function() {
      if (this.active) {
        return this.off();
      } else {
        return this.on();
      }
    };

    Stylish.prototype.destroy = function() {
      this.$wrapper.remove();
      this.$container.off('mouseover', '*', this.displayOver);
      this.$container.off('click', '*', this.displayEditor);
      this.$dialog.off('click', '.selector-level .btn', this.changeLevel);
      this.$dialog.off('click', '.btn-save', this.saveStyles);
      this.$dialog.off('change', "." + className.inputStoredSelectors, this.selectStyle);
      return this.$container.data('stylish', null);
    };

    Stylish.prototype.setStyleData = function(styles) {
      var selector, style;

      for (selector in styles) {
        style = styles[selector];
        this.addStyleToElement(selector, style);
      }
      return void 0;
    };

    Stylish.prototype.displayOver = function(e) {
      var $this;

      if (!this.active || this.editing) {
        return;
      }
      $this = $(e.target);
      this.$wrapper.width($this.outerWidth());
      this.$wrapper.height($this.outerHeight());
      this.$wrapper.offset($this.offset());
      return this.$wrapper.show();
    };

    Stylish.prototype.displayEditor = function(e) {
      var $this, options, sel, selector, storedStyles, styles;

      e.preventDefault();
      e.stopPropagation();
      if (!this.active) {
        return;
      }
      $this = $(e.target);
      if (this.editing) {
        if ($this.is('.stylish.popover') || $this.parents('.stylish.popover').size() > 0) {
          return;
        } else {
          this.closeDialog();
          return;
        }
      }
      this.editing = true;
      this.$element = $this;
      options = [templates.storeSelectorOption];
      selector = this.getCompleteSelector($this, 0);
      if (this.$element.data('styles')) {
        styles = this.$element.data('styles');
        for (sel in styles) {
          options.push("<option value=\"" + sel + "\">" + sel + "</option>");
        }
      }
      storedStyles = options.join('');
      this.$dialog.find('.size').html("" + ($this.width()) + "px x " + ($this.height()) + "px");
      this.$dialog.find("." + className.inputStoredSelectors).html(storedStyles);
      this.setInputValues(selector);
      return this.$dialog.show().offset({
        top: $this.offset().top + $this.outerHeight() + 7,
        left: $this.offset().left + 15
      });
    };

    Stylish.prototype.changeLevel = function(e) {
      var $this, level, selector;

      $this = $(e.currentTarget);
      level = this.$element.data('level') || 0;
      selector = "";
      if ($this.is('.select-up')) {
        if (level < this.$element.parents().size()) {
          level++;
        }
      } else {
        if (level > 0) {
          level--;
        }
      }
      selector = this.getCompleteSelector(this.$element, level);
      this.setInputValues(selector);
      return this.$element.data('level', level);
    };

    Stylish.prototype.saveStyles = function(e) {
      var cssText, selector, value,
        _this = this;

      cssText = this.$dialog.find("." + className.inputStyle).val().replace('\n', ' ');
      selector = this.$dialog.find("." + className.inputSelector).val();
      value = this.css2Json(cssText);
      return $.ajax({
        url: this.settings.post,
        data: {
          selector: selector,
          value: value
        },
        type: 'POST',
        success: function() {
          $(selector).css(value);
          _this.addStyleToElement(selector, value);
          return _this.closeDialog();
        },
        error: function() {}
      });
    };

    Stylish.prototype.selectStyle = function(e) {
      var $this, selector;

      $this = $(e.target);
      selector = $this.val();
      if (selector === '0') {
        selector = this.getCompleteSelector(this.$element, 0);
      }
      return this.setInputValues(selector);
    };

    return Stylish;

  })();
  $.fn.stylish = function(options) {
    return this.each(function() {
      var data, plugin;

      data = $(this).data('stylish');
      if (data === void 0) {
        plugin = new Stylish(this, options);
        return $(this).data('stylish', plugin);
      } else {
        if (typeof options === 'string') {
          return data[options]();
        }
      }
    });
  };
  Stylish.prototype.defaults = {
    post: void 0
  };
  return void 0;
})(jQuery, window);

/*
//@ sourceMappingURL=jquery.stylish.map
*/
